[config]
schemaVersion = "0.0.1"

[package]
namespace = "Gogas1"
name = "TPoVMod"
versionNumber = "0.1.3"
description = "Replaces Eigong themes with Through Patches of Violet by Mili"
websiteUrl = "https://github.com/Gogas1/NineSols-TPoV-mod"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-NineSolsAPI" = "1.3.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
